#ifndef UNKONWNEXCEPTIONOUPUT_H
#define UNKONWNEXCEPTIONOUPUT_H
namespace  {
    static constexpr const char* unkonwnExceptionOutput = "OOOOOOOOko:;;;;;;;;;;;;,''''''',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;:ccloddxxkkkkkxxxxxxxxddddddddddooo\nOOOOOOxo:;;;;;;;;;;;;;,,'''''''',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ccloddxxkkkkxxxxxdddddoooooolllllc\nkkxdoc:;;;;;;;;;;;;;;;,,''''''''',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ccloddxxkkkxxxxddddoooollllcccc:::\n\
::;;;;;;;;;;;;;;;;;;;,,,''''''''',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ccloddxxkkkkxxxdddooolllcccc:::;;;\n;;;;;;;;;;;;;;;;;;;;;;,,'''''''''',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ccloddxxkkkxxxxddooolllccc:::;;;,,\n;;;;;;;;;;;;;;;;;;;;;;,,'''''''''',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ccloddxxkkkxxxxddoolllccc:::;;;,,,\n\
;;;;;;;;;;;;;;;;;;;;;;,,,'''''''''',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cloddxxkkkxxxdddoolllccc:::;;;,,,\n;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,',;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cloodxxxxxxxxddooolllccc:::;;;,,,\n;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:clloddxxxxxdddooolllcccc::::;;;,,\n\
;;;;;;;;;;;;;;,'''',,;;;;;;;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:clooddddddddooollllccccc:::;;;,,\n;;;;;;;;;;;;;;,......',;;::::::;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:ccllooooooooollllllcccccc:::;;,,\n;;;;;;;;;;;;;;,....'.,odlc::::::::;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cccllllllllllllccccccccc:::;;,,\n\
;;;;;;;;;;;;;;'....'.:k0OOkdoc:;::;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::ccccccccccccccccccc::::;;,'\n;;;;;;;;;;;;;;,,,,...:kOOOOOOOxdl:;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;,,;:;,..\n;;;;;;;;;;;;;:cccc;'.,x0OOOOOOOOOkdoc;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''''''''''''''''''',;clodxkd,.'\n\
;;;;;;;;;;;;:cccccc:''lOOOOOOOOOOOOOOxoc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''''''''''''',;:loxkOOOOOOd,.'\n;;;;;;;;;;;;cccccccc:';xOOOOOOOOOOOOOOOOxoc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''''''''';:loxkOOOOOOOOOOOl...\n;;;;;;;;;;;:ccccccccc:,:kOOOOOOOOOOOOOOOOOOxo:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'''',;codkOOOOOOOOOOOOOOOk;...\n\
;;;;;;;;;;:cccccccc:::;,ckOOOOOOOOOOOOOOOOOOOkdc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,:coxkOOOOOOOOOOOOOOOOOOOl'..'\n;;;;;;;;;;:ccccccc:::;;,,ckOOOOOOOOOOOOOOOOOOOOOxc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cldkOOOOOOOOOOOOOOOOOOOOOOOd,.'''\n;;;;;;;;;:cccccccc::;;,,,':xOOOOOOOOOOOOOOOOOOOOOOdc;;;;::::ccccllllllllllllllllcc:cldkOOOOOOOOOOOOOOOOOOOOOOOOOOx,.''''\n\
;;;;;;;;;:cccccccc::;;,,''',oOOOOOOOOOOOOOOOOOOOOOOkxdxxkkkOOOOOOOOOOOOOOOOO00OOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOd;.'''''\n;;;;;;;;:::::::::::;;,,,''''':xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo;',,,'''\n;;;;;;;;;;;;;;;;;;;,,,,''''''',lkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOxc;;;;,,,,'\n\
;;;;;;,,,,,,,,,,,,,,,,'''''''''';lkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOko::::::;;;,,\n;;;;;,''''''''''''''''''''''''''..;lkOxdxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOxl::cccc:::;;,,\n;;;;;''''''''''''''''''''''''''''...,cdkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdxOOOxoc::cccccc:::;;,,\n\
;;;;,'''............''''''''''''''..,oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdolc;;:::ccccc:::;;;,,\n;;;,'.................''''''''''''.,oOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOx:,;;::::::::::;;;,,,\n;;;'...................''''''''''''lOOOOOOOOOOkdlcldOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdollokOOOOOOOOOOOOOkc,;;;;:::::;;;;,,,,\n\
;;,'...................''''''',,,'ckOOOOOOOOOdokOl''lkOOOOOOOOOOOOOOOOOOOOOOOOOkodOx;.;xOOOOOOOOOOOOOkc,;;;;;;;;;;;,,,,'\n;,'.....................'''',,,,';xOOOOOOOOOk::kOl'.,d0OOOOOOOOOOOOOOOOOOOOOOOOl;dOx;..cOOOOOOOOOOOOOOx;,;;;,,,,,,,,,,''\n;'......................'''',,,,,oOOOOOOOOOOOc.'''..;xOOOOOOOOOOOOOOOOOOOOOOOOOd,.'''.'oOOOOOOOOOOOOOOOl,,,,,,,,,,,,''''\n\
,'......................'''',,,,ckOOOOOOOOOOOkl;,',:xOOOOOOOOOOOOOOOOOOOOOOOOOOOd:,',;okOOOOOOOOOOOOOOOk:',',,'','''''''\n'.......................'''',,,;dOOOOOOOOOOOOOOkxxkOOOOOOOOOOOxxxkOOOOOOOOOOOOOOOOkxxOOOOOOOOOOOOOOOOOOOo,''''''''''''''\n'.......................''',,,,lOOOOOOOOOOOOOOOOOOOOOOOOOOOOOd;'',oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0k:''''''''''''''\n\
'......................'''',,,;dOkxdoooodkOOOOOOOOOOOOOOOOOOOOxdddkOOOOOOOOOOOOOOOOOOOOOOxdooooddkOOOOOOOd,','''''''''''\n'''..................'''',,,,,ckxlccccccccokOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOxocccccccccokOOOOOkc',,,,,,,,,,''\n''''''''''''''''''''',,,,,;;;,oxlccccccccccdOOOOOOOOOOOOOOOOOOOOOkkkkOOOOOOOOOOOOOOOOOklcccccccccccoOOOOOOd;,;,,,,,,,,''\n\
''''',,,,,,,,,,,,,,,,,;;;;;;;;dkoccccccccccxOOOOOOOOOOOOOOOkxdooooooooookOOOOOOOOOOOOOklcccccccccccoOOOOOOkc,;;;;;;,,,,'\n,,,,,,,,,;;;;;;;;;;;;;;;::::;;oOkdlcccccloxOOOOOOOOOOOOOOOxlclodxxxxxxdlcxOOOOOOOOOOOOOxlcccccccccokOOOOOOOd;;::;;;;;,,'\n,,,,;;;;;;:::::::::::::::::::;lOOOOkxxxkkOOOOOOOOOOOOOOOOOocddxxxxxxxxxdcoOOOOOOOOOOOOOOkxdooooodkOOOOOOOOOkc;:::::;;;,,\n\
,,;;;;::::::ccccccccccccccccc::dOOOOOOOOOOOOOOOOOOOOOOOOOOxc:lxxxxxxxxxdcoOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOd::c::::;;,,\n,,;;;::::ccccccccccccccccccccc:cxOOOOOOOOOOOOOOOOOOOOOOOOOOxolloddxxxxdlcxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0kc:cc:::;;,,\n,,;;;::::cccccccccccccccccccccc;cxOOOOOOOOOOOOOOOOOOOOOOOOOOOOxdooooooodkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo:cc:::;;,,\n\
,,;;;:::::cccccccccccccccccccc::;cxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0x::c:::;;,,\n,,;;;;:::::ccccccccccccccccc:::::;:xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkc;:::;;;,,\n,,;;;;;;:::::::::::::::::::::::::;,:xOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo;::;;;,,'\n\
;;;;;;;;;;:::::::::::::::::::;;;;;;,lOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0d;;;;;,,,'\n;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0k:,;,,,,,'\n:;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,':k0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOc',,,,'''\n\
::;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,',oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOl''',''''\n";

}
#endif // UNKONWNEXCEPTIONOUPUT_H
